---

# NOTE: This must be run AFTER installing custom kernel AND restarting..
# (We also need linux-headers-xxx that should be installed with kernel role.)

- name: Add packages for compiling VBoxLinuxAdditions
  apt:
    name:
      - build-essential
    state: present

- name: Ensure cdrom mount point exists
  file:
    path: /media/cdrom
    state: directory

- name: Mount cdrom
  mount:
    name: /media/cdrom
    src: /dev/cdrom
    fstype: iso9660
    state: mounted

- name: Install VBoxLinuxAdditions
  command: ./VBoxLinuxAdditions.run
  args:
    chdir: /media/cdrom
